### ISSUE TITLE
Wrong output-something missing in algorithm

### ISSUE THREAD

**Issue by mr-robot77** [mr-robot77/Courses-Project#1]
This code has an issue that get wrong output
Something is missing in implementation of algorithm
What is forgotten and not mentioned!?

**Comment by akj2018** [comment]
Hi @mr-robot77, can you also specific which algorithm is giving wrong output along with 
- inputs
- expected output
- incorrect output.

**Comment by mr-robot77** [comment]
in the python ch2 string folder
returner program has an issue in runtime output
this program is about a safe with k rotating locks with a sequence of numbers from 1 to 9 and our mission is finding to k-digit code from input and in the output should give the minimum number of rotation of the wheels for the number to be equal to the code.
if we get this input:
`3
123
241356789
987546231
956874231`
our expected output should be this:
`7`
but because of something is missing in define of algorithm of this problem, so we get this wrong output:
`2148921431256`

**Comment by akj2018** [comment]
Hey,
1. I not able to understand what you are trying to achieve
2. The code implies that locks is a list of sub lists but the input provided is unclear about how many elements goes in each iteration
Eg. 

k = 3
code = 123

for k = 1
    input can be 241356789 
OR
    input can be 241356789 987546231
OR
    input can be 241356789 987546231 956874231

Therefore, please provide an input separated by new line

3. if number in locks[i]: will always result in False since it's checking if 1 is an element in a sub list and this is never the case
Therefore, my answer in always 0

**Comment by mr-robot77** [comment]
i solved the issues and change the code
now it's worked correctly
